spring.application.name=backend

# Usamos variables con valores por defecto (lo que va después de los dos puntos)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/gschedule_db?serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:alex}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# El puerto dinámico es CRUCIAL para Render
server.port=${PORT:8080}

# Hibernate ddl auto
spring.jpa.hibernate.ddl-auto=update

# Configuración de logs (puedes bajar el nivel en producción si quieres menos ruido)
spring.jpa.show-sql=true
spring.web.error.include-message=always